"""
RENI — Metadata & Provenance Forensics Engine
Inspects PDF metadata, EXIF data, and tool fingerprints to detect doctored documents.
"""
import os
import fitz  # PyMuPDF
from datetime import datetime


# Tools that indicate consumer-grade editing (suspicious for official documents)
SUSPICIOUS_PRODUCERS = [
    "canva", "photoshop", "gimp", "paint.net", "inkscape",
    "camscanner", "adobe illustrator", "foxit", "smallpdf",
    "ilovepdf", "sejda", "pdfcandy", "online", "wps office",
    "libreoffice draw", "pixlr", "snapseed",
]

# Tools expected for genuine institutional documents
INSTITUTIONAL_PRODUCERS = [
    "govprint", "sap", "oracle", "digilocker", "national informatics centre",
    "nic", "tcs", "infosys", "hcl", "wipro",
]


class MetadataForensics:
    """
    Inspects document metadata for provenance clues.
    
    - PDF: Producer, Creator, creation/modification timestamps, page count
    - Image: EXIF data, camera info, software tags
    - Structural: embedded object count, font count, unusual PDF structure
    """

    def analyze(self, file_path):
        """Route to the appropriate analyzer based on file type."""
        ext = os.path.splitext(file_path)[1].lower()
        if ext == '.pdf':
            return self._analyze_pdf(file_path)
        elif ext in ['.jpg', '.jpeg', '.png', '.tiff', '.bmp', '.webp']:
            return self._analyze_image(file_path)
        return {
            "agent": "Provenance",
            "findings": [{"type": "UNKNOWN_FORMAT", "description": f"Unsupported format: {ext}", "severity": 0}],
            "belief_mass": {"forged": 0.0, "genuine": 0.0, "uncertain": 1.0},
            "metadata_raw": {},
        }

    def _analyze_pdf(self, file_path):
        print("  [PROVENANCE] Inspecting PDF metadata layers...")
        findings = []
        belief = {"forged": 0.05, "genuine": 0.50, "uncertain": 0.45}
        raw_meta = {}

        try:
            doc = fitz.open(file_path)
            meta = doc.metadata or {}
            page_count = len(doc)

            raw_meta = {
                "producer": meta.get("producer", ""),
                "creator": meta.get("creator", ""),
                "title": meta.get("title", ""),
                "subject": meta.get("subject", ""),
                "author": meta.get("author", ""),
                "creationDate": meta.get("creationDate", ""),
                "modDate": meta.get("modDate", ""),
                "format": meta.get("format", ""),
                "page_count": page_count,
            }

            # --- Check 1: Suspicious creation tool ---
            producer = (meta.get("producer", "") or "").lower()
            creator = (meta.get("creator", "") or "").lower()
            tool_string = f"{producer} {creator}"

            suspicious_match = None
            for tool in SUSPICIOUS_PRODUCERS:
                if tool in tool_string:
                    suspicious_match = tool.title()
                    break

            if suspicious_match:
                findings.append({
                    "type": "SUSPICIOUS_TOOL",
                    "description": (
                        f"Document was created/produced with '{suspicious_match}'. "
                        "Genuine institutional certificates are typically generated by "
                        "government or enterprise document management systems, not consumer editing tools."
                    ),
                    "severity": 0.72,
                    "shap_weight": 0.31,
                    "raw": {"producer": producer, "creator": creator},
                })
                belief = {"forged": 0.65, "genuine": 0.15, "uncertain": 0.20}
            else:
                # Check if it's an institutional tool
                is_institutional = any(t in tool_string for t in INSTITUTIONAL_PRODUCERS)
                if is_institutional:
                    findings.append({
                        "type": "INSTITUTIONAL_TOOL",
                        "description": f"Document producer '{producer or creator}' matches known institutional systems.",
                        "severity": 0.05,
                        "shap_weight": 0.10,
                    })
                    belief = {"forged": 0.05, "genuine": 0.80, "uncertain": 0.15}

            # --- Check 2: Missing or stripped metadata ---
            if not producer and not creator:
                findings.append({
                    "type": "METADATA_STRIPPED",
                    "description": (
                        "PDF metadata is empty — no Producer or Creator field. "
                        "Metadata stripping is a known anti-forensic technique used to conceal document origin."
                    ),
                    "severity": 0.50,
                    "shap_weight": 0.18,
                })
                belief["forged"] = max(belief["forged"], 0.40)
                belief["uncertain"] = 0.30

            # --- Check 3: Timestamp consistency ---
            creation = meta.get("creationDate", "")
            modification = meta.get("modDate", "")
            if creation and modification:
                try:
                    c_date = self._parse_pdf_date(creation)
                    m_date = self._parse_pdf_date(modification)
                    if c_date and m_date:
                        delta = (m_date - c_date).total_seconds()
                        if delta < 0:
                            findings.append({
                                "type": "TIMESTAMP_ANOMALY",
                                "description": (
                                    "Modification date precedes creation date — a physical impossibility "
                                    "that indicates timestamp tampering."
                                ),
                                "severity": 0.85,
                                "shap_weight": 0.25,
                            })
                            belief = {"forged": 0.80, "genuine": 0.05, "uncertain": 0.15}
                        elif delta > 0 and delta < 60:
                            findings.append({
                                "type": "RAPID_EDIT",
                                "description": (
                                    f"Document was modified only {int(delta)} seconds after creation. "
                                    "This pattern is consistent with automated document generation tools."
                                ),
                                "severity": 0.20,
                                "shap_weight": 0.08,
                            })
                except Exception:
                    pass

            # --- Check 4: Embedded font and object analysis ---
            total_fonts = set()
            total_images = 0
            for page in doc:
                fonts = page.get_fonts()
                for f in fonts:
                    total_fonts.add(f[3])  # font name
                images = page.get_images()
                total_images += len(images)

            raw_meta["font_count"] = len(total_fonts)
            raw_meta["image_count"] = total_images
            raw_meta["fonts_used"] = list(total_fonts)[:10]

            if len(total_fonts) > 6:
                findings.append({
                    "type": "EXCESSIVE_FONTS",
                    "description": (
                        f"Document uses {len(total_fonts)} distinct fonts. "
                        "Official documents typically use 1-3 fonts. Excessive font variety "
                        "suggests content was assembled from multiple sources."
                    ),
                    "severity": 0.45,
                    "shap_weight": 0.12,
                })
                belief["forged"] = min(belief["forged"] + 0.15, 0.90)

            doc.close()

        except Exception as e:
            findings.append({
                "type": "PARSE_ERROR",
                "description": f"Failed to parse PDF metadata: {str(e)}",
                "severity": 0.10,
            })

        if not findings:
            findings.append({
                "type": "METADATA_CLEAN",
                "description": "No provenance anomalies detected in document metadata.",
                "severity": 0.05,
                "shap_weight": 0.10,
            })

        print(f"  [PROVENANCE] Done. {len(findings)} finding(s). Belief(forged)={belief['forged']:.2f}")
        return {
            "agent": "Provenance",
            "findings": findings,
            "belief_mass": belief,
            "metadata_raw": raw_meta,
        }

    def _analyze_image(self, file_path):
        print("  [PROVENANCE] Inspecting image metadata (EXIF)...")
        findings = []
        belief = {"forged": 0.05, "genuine": 0.50, "uncertain": 0.45}
        raw_meta = {}

        try:
            from PIL import Image
            from PIL.ExifTags import TAGS

            img = Image.open(file_path)
            exif_raw = img._getexif()

            if exif_raw:
                for tag_id, value in exif_raw.items():
                    tag_name = TAGS.get(tag_id, tag_id)
                    if isinstance(value, (str, int, float)):
                        raw_meta[str(tag_name)] = str(value)

                software = raw_meta.get("Software", "").lower()
                for tool in SUSPICIOUS_PRODUCERS:
                    if tool in software:
                        findings.append({
                            "type": "SUSPICIOUS_SOFTWARE",
                            "description": f"Image EXIF Software field contains '{software}'. Consumer editing tool detected.",
                            "severity": 0.60,
                            "shap_weight": 0.25,
                        })
                        belief = {"forged": 0.55, "genuine": 0.20, "uncertain": 0.25}
                        break
            else:
                findings.append({
                    "type": "NO_EXIF",
                    "description": (
                        "Image contains no EXIF metadata. This could indicate the image was "
                        "processed through a tool that strips metadata, or was created digitally."
                    ),
                    "severity": 0.30,
                    "shap_weight": 0.12,
                })
                belief = {"forged": 0.25, "genuine": 0.35, "uncertain": 0.40}

            img.close()

        except Exception as e:
            findings.append({
                "type": "EXIF_ERROR",
                "description": f"Could not read image metadata: {str(e)}",
                "severity": 0.05,
            })

        if not findings:
            findings.append({
                "type": "METADATA_CLEAN",
                "description": "Image metadata appears consistent. No provenance anomalies detected.",
                "severity": 0.05,
            })

        print(f"  [PROVENANCE] Done. {len(findings)} finding(s).")
        return {
            "agent": "Provenance",
            "findings": findings,
            "belief_mass": belief,
            "metadata_raw": raw_meta,
        }

    @staticmethod
    def _parse_pdf_date(date_str):
        """Parse PDF date format D:YYYYMMDDHHmmSS into datetime."""
        try:
            cleaned = date_str.replace("D:", "").split("+")[0].split("-")[0].split("Z")[0]
            if len(cleaned) >= 14:
                return datetime.strptime(cleaned[:14], "%Y%m%d%H%M%S")
            elif len(cleaned) >= 8:
                return datetime.strptime(cleaned[:8], "%Y%m%d")
        except Exception:
            return None
